In [31]:
import pandas as pd

In [32]:
csv_path = ("../U.S._Chronic_Disease_Indicators__CDI_.csv")

csv_df = pd.read_csv(csv_path)
low_memory=False
csv_df

/Users/Pariah/anaconda3/envs/PythonData3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (7,10,18,19,20,21,23,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
5,2016,2016,CA,California,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,6,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
6,2016,2016,CO,Colorado,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,8,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
7,2016,2016,CT,Connecticut,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,9,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
8,2016,2016,DE,Delaware,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,10,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
9,2016,2016,DC,District of Columbia,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,11,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
10,2016,2016,FL,Florida,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,12,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
11,2016,2016,GA,Georgia,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,13,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
12,2016,2016,HI,Hawaii,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,15,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
13,2016,2016,ID,Idaho,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,16,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
14,2016,2016,IL,Illinois,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,17,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
15,2016,2016,IN,Indiana,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,18,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
16,2016,2016,IA,Iowa,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,19,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
17,2016,2016,KS,Kansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,20,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
18,2016,2016,KY,Kentucky,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,21,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
19,2016,2016,LA,Louisiana,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,22,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
20,2016,2016,ME,Maine,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,23,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
21,2016,2016,MD,Maryland,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,24,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
22,2016,2016,MA,Massachusetts,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,25,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
23,2016,2016,MI,Michigan,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,26,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
24,2016,2016,MN,Minnesota,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,27,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
25,2016,2016,MS,Mississippi,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,28,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
26,2016,2016,MO,Missouri,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,29,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
27,2016,2016,MT,Montana,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,30,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
28,2016,2016,NE,Nebraska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,31,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
29,2016,2016,NV,Nevada,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,32,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519688,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Age-adjusted Prevalence,...,78,ORH,ORH4_3,AGEADJPREV,RACE,OTH,NaN,NaN,NaN,NaN
519689,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Age-adjusted Prevalence,...,78,ORH,ORH4_3,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519690,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Age-adjusted Prevalence,...,78,ORH,ORH4_3,AGEADJPREV,RACE,WHT,NaN,NaN,NaN,NaN
519691,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
519692,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
519693,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,RACE,HIS,NaN,NaN,NaN,NaN
519694,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
519695,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,RACE,MRC,NaN,NaN,NaN,NaN
519696,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,RACE,OTH,NaN,NaN,NaN,NaN
519697,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519698,2014,2014,VI,Virgin Islands,BRFSS,Oral Health,No tooth loss among adults aged 18-64 years,NaN,%,Crude Prevalence,...,78,ORH,ORH4_3,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
519699,2014,2014,RI,Rhode Island,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,44,OVC,OVC3_1,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
519700,2015,2015,SC,South Carolina,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,45,OVC,OVC3_1,CRDPREV,RACE,AIAN,NaN,NaN,NaN,NaN
519701,2015,2015,SD,South Dakota,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,46,OVC,OVC3_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
519702,2015,2015,SD,South Dakota,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,46,OVC,OVC3_1,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
519703,2016,2016,PR,Puerto Rico,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,72,OVC,OVC3_1,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
519704,2016,2016,PR,Puerto Rico,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,72,OVC,OVC3_1,CRDPREV,RACE,AIAN,NaN,NaN,NaN,NaN
519705,2016,2016,PR,Puerto Rico,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,72,OVC,OVC3_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
519706,2016,2016,PR,Puerto Rico,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,72,OVC,OVC3_1,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
519707,2012,2012,US,United States,BRFSS,Overarching Conditions,Prevalence of sufficient sleep among adults ag...,NaN,%,Age-adjusted Prevalence,...,59,OVC,OVC8_0,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519708,2012,2012,US,United States,BRFSS,Overarching Conditions,Prevalence of sufficient sleep among adults ag...,NaN,%,Crude Prevalence,...,59,OVC,OVC8_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519709,2015,2015,VI,Virgin Islands,YRBSS,Tobacco,Current cigarette smoking among youth,NaN,%,Crude Prevalence,...,78,TOB,TOB1_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519710,2015,2015,VT,Vermont,YRBSS,Tobacco,Current cigarette smoking among youth,NaN,%,Crude Prevalence,...,50,TOB,TOB1_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519711,2015,2015,CT,Connecticut,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,9,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519712,2015,2015,DC,District of Columbia,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,11,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519713,2015,2015,FL,Florida,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,12,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519714,2015,2015,HI,Hawaii,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,15,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519715,2015,2015,VI,Virgin Islands,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,78,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519716,2015,2015,VT,Vermont,YRBSS,Tobacco,Current smokeless tobacco use among youth,NaN,%,Crude Prevalence,...,50,TOB,TOB2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
519717,2013,2013,NM,New Mexico,ACS 1-Year Estimates,Disability,Disability among adults aged >= 65 years,NaN,%,Crude Prevalence,...,35,DIS,DIS1_0,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN

In [33]:
csv_df = csv_df[[(x == 'Crude Prevalence') for x in csv_df["DataValueType"]]]
csv_df["DataValueType"].unique()
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [34]:
csv_df["Topic"].unique()

array(['Alcohol', 'Arthritis', 'Asthma', 'Cancer', 'Diabetes',
       'Chronic Obstructive Pulmonary Disease', 'Oral Health',
       'Cardiovascular Disease', 'Immunization', 'Mental Health',
       'Chronic Kidney Disease',
       'Nutrition, Physical Activity, and Weight Status', 'Older Adults',
       'Tobacco', 'Overarching Conditions', 'Reproductive Health',
       'Disability'], dtype=object)

In [35]:
del csv_df["DataSource"]

csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,Response,DataValueUnit,DataValueType,DataValue,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,16.9,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,13,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,18.2,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,15.6,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,15,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [36]:
del csv_df["Response"]


csv_df.head

<bound method NDFrame.head of         YearStart  YearEnd LocationAbbr          LocationDesc  \
0            2016     2016           US         United States
1            2016     2016           AL               Alabama
2            2016     2016           AK                Alaska
3            2016     2016           AZ               Arizona
4            2016     2016           AR              Arkansas
5            2016     2016           CA            California
6            2016     2016           CO              Colorado
7            2016     2016           CT           Connecticut
8            2016     2016           DE              Delaware
9            2016     2016           DC  District of Columbia
10           2016     2016           FL               Florida
11           2016     2016           GA               Georgia
12           2016     2016           HI                Hawaii
13           2016     2016           ID                 Idaho
14           2016     2016           IL              Illinois
15           2016     2016           IN               Indiana
16           2016     2016           IA                  Iowa
17           2016     2016           KS                Kansas
18           2016     2016           KY              Kentucky
19           2016     2016           LA             Louisiana
20           2016     2016           ME                 Maine
21           2016     2016           MD              Maryland
22           2016     2016           MA         Massachusetts
23           2016     2016           MI              Michigan
24           2016     2016           MN             Minnesota
25           2016     2016           MS           Mississippi
26           2016     2016           MO              Missouri
27           2016     2016           MT               Montana
28           2016     2016           NE              Nebraska
29           2016     2016           NV                Nevada
...           ...      ...          ...                   ...
519679       2014     2014           VI        Virgin Islands
519680       2014     2014           VI        Virgin Islands
519681       2014     2014           VI        Virgin Islands
519682       2014     2014           VI        Virgin Islands
519691       2014     2014           VI        Virgin Islands
519692       2014     2014           VI        Virgin Islands
519693       2014     2014           VI        Virgin Islands
519694       2014     2014           VI        Virgin Islands
519695       2014     2014           VI        Virgin Islands
519696       2014     2014           VI        Virgin Islands
519697       2014     2014           VI        Virgin Islands
519698       2014     2014           VI        Virgin Islands
519699       2014     2014           RI          Rhode Island
519700       2015     2015           SC        South Carolina
519701       2015     2015           SD          South Dakota
519702       2015     2015           SD          South Dakota
519703       2016     2016           PR           Puerto Rico
519704       2016     2016           PR           Puerto Rico
519705       2016     2016           PR           Puerto Rico
519706       2016     2016           PR           Puerto Rico
519708       2012     2012           US         United States
519709       2015     2015           VI        Virgin Islands
519710       2015     2015           VT               Vermont
519711       2015     2015           CT           Connecticut
519712       2015     2015           DC  District of Columbia
519713       2015     2015           FL               Florida
519714       2015     2015           HI                Hawaii
519715       2015     2015           VI        Virgin Islands
519716       2015     2015           VT               Vermont
519717       2013     2013           NM            New Mexico

                         Topic  \
0                      Alcohol
1                      Alcohol
2                      Alcohol
3                      Alcohol
4                      Alcohol
5                      Alcohol
6                      Alcohol
7                      Alcohol
8                      Alcohol
9                      Alcohol
10                     Alcohol
11                     Alcohol
12                     Alcohol
13                     Alcohol
14                     Alcohol
15                     Alcohol
16                     Alcohol
17                     Alcohol
18                     Alcohol
19                     Alcohol
20                     Alcohol
21                     Alcohol
22                     Alcohol
23                     Alcohol
24                     Alcohol
25                     Alcohol
26                     Alcohol
27                     Alcohol
28                     Alcohol
29                     Alcohol
...                        ...
519679             Oral Health
519680             Oral Health
519681             Oral Health
519682             Oral Health
519691             Oral Health
519692             Oral Health
519693             Oral Health
519694             Oral Health
519695             Oral Health
519696             Oral Health
519697             Oral Health
519698             Oral Health
519699  Overarching Conditions
519700  Overarching Conditions
519701  Overarching Conditions
519702  Overarching Conditions
519703  Overarching Conditions
519704  Overarching Conditions
519705  Overarching Conditions
519706  Overarching Conditions
519708  Overarching Conditions
519709                 Tobacco
519710                 Tobacco
519711                 Tobacco
519712                 Tobacco
519713                 Tobacco
519714                 Tobacco
519715                 Tobacco
519716                 Tobacco
519717              Disability

                                                 Question DataValueUnit  \
0       Binge drinking prevalence among adults aged >=...             %
1       Binge drinking prevalence among adults aged >=...             %
2       Binge drinking prevalence among adults aged >=...             %
3       Binge drinking prevalence among adults aged >=...             %
4       Binge drinking prevalence among adults aged >=...             %
5       Binge drinking prevalence among adults aged >=...             %
6       Binge drinking prevalence among adults aged >=...             %
7       Binge drinking prevalence among adults aged >=...             %
8       Binge drinking prevalence among adults aged >=...             %
9       Binge drinking prevalence among adults aged >=...             %
10      Binge drinking prevalence among adults aged >=...             %
11      Binge drinking prevalence among adults aged >=...             %
12      Binge drinking prevalence among adults aged >=...             %
13      Binge drinking prevalence among adults aged >=...             %
14      Binge drinking prevalence among adults aged >=...             %
15      Binge drinking prevalence among adults aged >=...             %
16      Binge drinking prevalence among adults aged >=...             %
17      Binge drinking prevalence among adults aged >=...             %
18      Binge drinking prevalence among adults aged >=...             %
19      Binge drinking prevalence among adults aged >=...             %
20      Binge drinking prevalence among adults aged >=...             %
21      Binge drinking prevalence among adults aged >=...             %
22      Binge drinking prevalence among adults aged >=...             %
23      Binge drinking prevalence among adults aged >=...             %
24      Binge drinking prevalence among adults aged >=...             %
25      Binge drinking prevalence among adults aged >=...             %
26      Binge drinking prevalence among adults aged >=...             %
27      Binge drinking prevalence among adults aged >=...             %
28      Binge drinking prevalence among adults aged >=...             %
29      Binge drinking prevalence among adults aged >=...             %
...                                                   ...           ...
519679  Six or more teeth lost among adults aged >= 65...             %
519680  Six or more teeth lost among adults aged >= 65...             %
519681  Six or more teeth lost among adults aged >= 65...             %
519682  Six or more teeth lost among adults aged >= 65...             %
519691        No tooth loss among adults aged 18-64 years             %
519692        No tooth loss among adults aged 18-64 years             %
519693        No tooth loss among adults aged 18-64 years             %
519694        No tooth loss among adults aged 18-64 years             %
519695        No tooth loss among adults aged 18-64 years             %
519696        No tooth loss among adults aged 18-64 years             %
519697        No tooth loss among adults aged 18-64 years             %
519698        No tooth loss among adults aged 18-64 years             %
519699                                            Poverty             %
519700                                            Poverty             %
519701                                            Poverty             %
519702                                            Poverty             %
519703                                            Poverty             %
519704                                            Poverty             %
519705                                            Poverty             %
519706                                            Poverty             %
519708  Prevalence of sufficient sleep among adults ag...             %
519709              Current cigarette smoking among youth             %
519710              Current cigarette smoking among youth             %
519711          Current smokeless tobacco use among youth             %
519712          Current smokeless tobacco use among youth             %
519713          Current smokeless tobacco use among youth             %
519714          Current smokeless tobacco use among youth             %
519715          Current smokeless tobacco use among youth             %
519716          Current smokeless tobacco use among youth             %
519717           Disability among adults aged >= 65 years             %

           DataValueType DataValue  DataValueAlt  ... LocationID TopicID  \
0       Crude Prevalence      16.9          16.9  ...         59     ALC
1       Crude Prevalence        13          13.0  ...          1     ALC
2       Crude Prevalence      18.2          18.2  ...          2     ALC
3       Crude Prevalence      15.6          15.6  ...          4     ALC
4       Crude Prevalence        15          15.0  ...          5     ALC
5       Crude Prevalence      16.3          16.3  ...          6     ALC
6       Crude Prevalence        19          19.0  ...          8     ALC
7       Crude Prevalence      16.7          16.7  ...          9     ALC
8       Crude Prevalence        17          17.0  ...         10     ALC
9       Crude Prevalence      25.6          25.6  ...         11     ALC
10      Crude Prevalence      15.5          15.5  ...         12     ALC
11      Crude Prevalence      13.3          13.3  ...         13     ALC
12      Crude Prevalence      18.6          18.6  ...         15     ALC
13      Crude Prevalence      16.1          16.1  ...         16     ALC
14      Crude Prevalence      19.9          19.9  ...         17     ALC
15      Crude Prevalence      17.5          17.5  ...         18     ALC
16      Crude Prevalence      21.2          21.2  ...         19     ALC
17      Crude Prevalence        16          16.0  ...         20     ALC
18      Crude Prevalence      14.6          14.6  ...         21     ALC
19      Crude Prevalence      16.9          16.9  ...         22     ALC
20      Crude Prevalence      18.3          18.3  ...         23     ALC
21      Crude Prevalence      15.3          15.3  ...         24     ALC
22      Crude Prevalence      17.8          17.8  ...         25     ALC
23      Crude Prevalence        19          19.0  ...         26     ALC
24      Crude Prevalence      21.3          21.3  ...         27     ALC
25      Crude Prevalence      12.3          12.3  ...         28     ALC
26      Crude Prevalence      18.4          18.4  ...         29     ALC
27      Crude Prevalence      18.9          18.9  ...         30     ALC
28      Crude Prevalence        20          20.0  ...         31     ALC
29      Crude Prevalence      15.8          15.8  ...         32     ALC
...                  ...       ...           ...  ...        ...     ...
519679  Crude Prevalence       NaN           NaN  ...         78     ORH
519680  Crude Prevalence       NaN           NaN  ...         78     ORH
519681  Crude Prevalence       NaN           NaN  ...         78     ORH
519682  Crude Prevalence       NaN           NaN  ...         78     ORH
519691  Crude Prevalence       NaN           NaN  ...         78     ORH
519692  Crude Prevalence       NaN           NaN  ...         78     ORH
519693  Crude Prevalence       NaN           NaN  ...         78     ORH
519694  Crude Prevalence       NaN           NaN  ...         78     ORH
519695  Crude Prevalence       NaN           NaN  ...         78     ORH
519696  Crude Prevalence       NaN           NaN  ...         78     ORH
519697  Crude Prevalence       NaN           NaN  ...         78     ORH
519698  Crude Prevalence       NaN           NaN  ...         78     ORH
519699  Crude Prevalence       NaN           NaN  ...         44     OVC
519700  Crude Prevalence       NaN           NaN  ...         45     OVC
519701  Crude Prevalence       NaN           NaN  ...         46     OVC
519702  Crude Prevalence       NaN           NaN  ...         46     OVC
519703  Crude Prevalence       NaN           NaN  ...         72     OVC
519704  Crude Prevalence       NaN           NaN  ...         72     OVC
519705  Crude Prevalence       NaN           NaN  ...         72     OVC
519706  Crude Prevalence       NaN           NaN  ...         72     OVC
519708  Crude Prevalence       NaN           NaN  ...         59     OVC
519709  Crude Prevalence       NaN           NaN  ...         78     TOB
519710  Crude Prevalence       NaN           NaN  ...         50     TOB
519711  Crude Prevalence       NaN           NaN  ...          9     TOB
519712  Crude Prevalence       NaN           NaN  ...         11     TOB
519713  Crude Prevalence       NaN           NaN  ...         12     TOB
519714  Crude Prevalence       NaN           NaN  ...         15     TOB
519715  Crude Prevalence       NaN           NaN  ...         78     TOB
519716  Crude Prevalence       NaN           NaN  ...         50     TOB
519717  Crude Prevalence       NaN           NaN  ...         35     DIS

        QuestionID  DataValueTypeID StratificationCategoryID1  \
0           ALC2_2          CRDPREV                   OVERALL
1           ALC2_2          CRDPREV                   OVERALL
2           ALC2_2          CRDPREV                   OVERALL
3           ALC2_2          CRDPREV                   OVERALL
4           ALC2_2          CRDPREV                   OVERALL
5           ALC2_2          CRDPREV                   OVERALL
6           ALC2_2          CRDPREV                   OVERALL
7           ALC2_2          CRDPREV                   OVERALL
8           ALC2_2          CRDPREV                   OVERALL
9           ALC2_2          CRDPREV                   OVERALL
10          ALC2_2          CRDPREV                   OVERALL
11          ALC2_2          CRDPREV                   OVERALL
12          ALC2_2          CRDPREV                   OVERALL
13          ALC2_2          CRDPREV                   OVERALL
14          ALC2_2          CRDPREV                   OVERALL
15          ALC2_2          CRDPREV                   OVERALL
16          ALC2_2          CRDPREV                   OVERALL
17          ALC2_2          CRDPREV                   OVERALL
18          ALC2_2          CRDPREV                   OVERALL
19          ALC2_2          CRDPREV                   OVERALL
20          ALC2_2          CRDPREV                   OVERALL
21          ALC2_2          CRDPREV                   OVERALL
22          ALC2_2          CRDPREV                   OVERALL
23          ALC2_2          CRDPREV                   OVERALL
24          ALC2_2          CRDPREV                   OVERALL
25          ALC2_2          CRDPREV                   OVERALL
26          ALC2_2          CRDPREV                   OVERALL
27          ALC2_2          CRDPREV                   OVERALL
28          ALC2_2          CRDPREV                   OVERALL
29          ALC2_2          CRDPREV                   OVERALL
...            ...              ...                       ...
519679      ORH4_2          CRDPREV                      RACE
519680      ORH4_2          CRDPREV                      RACE
519681      ORH4_2          CRDPREV                   OVERALL
519682      ORH4_2          CRDPREV                      RACE
519691      ORH4_3          CRDPREV                      RACE
519692      ORH4_3          CRDPREV                    GENDER
519693      ORH4_3          CRDPREV                      RACE
519694      ORH4_3          CRDPREV                    GENDER
519695      ORH4_3          CRDPREV                      RACE
519696      ORH4_3          CRDPREV                      RACE
519697      ORH4_3          CRDPREV                   OVERALL
519698      ORH4_3          CRDPREV                      RACE
519699      OVC3_1          CRDPREV                      RACE
519700      OVC3_1          CRDPREV                      RACE
519701      OVC3_1          CRDPREV                      RACE
519702      OVC3_1          CRDPREV                      RACE
519703      OVC3_1          CRDPREV                      RACE
519704      OVC3_1          CRDPREV                      RACE
519705      OVC3_1          CRDPREV                      RACE
519706      OVC3_1          CRDPREV                      RACE
519708      OVC8_0          CRDPREV                   OVERALL
519709      TOB1_1          CRDPREV                   OVERALL
519710      TOB1_1          CRDPREV                   OVERALL
519711      TOB2_1          CRDPREV                   OVERALL
519712      TOB2_1          CRDPREV                   OVERALL
519713      TOB2_1          CRDPREV                   OVERALL
519714      TOB2_1          CRDPREV                   OVERALL
519715      TOB2_1          CRDPREV                   OVERALL
519716      TOB2_1          CRDPREV                   OVERALL
519717      DIS1_0          CRDPREV                      RACE

       StratificationID1 StratificationCategoryID2 StratificationID2  \
0                    OVR                       NaN               NaN
1                    OVR                       NaN               NaN
2                    OVR                       NaN               NaN
3                    OVR                       NaN               NaN
4                    OVR                       NaN               NaN
5                    OVR                       NaN               NaN
6                    OVR                       NaN               NaN
7                    OVR                       NaN               NaN
8                    OVR                       NaN               NaN
9                    OVR                       NaN               NaN
10                   OVR                       NaN               NaN
11                   OVR                       NaN               NaN
12                   OVR                       NaN               NaN
13                   OVR                       NaN               NaN
14                   OVR                       NaN               NaN
15                   OVR                       NaN               NaN
16                   OVR                       NaN               NaN
17                   OVR                       NaN               NaN

In [37]:
del csv_df["DataValueType"]

csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,DataValueFootnoteSymbol,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,*,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,NaN,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,NaN,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,NaN,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,NaN,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [38]:
del csv_df["TopicID"]

csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,DataValueFootnoteSymbol,...,ResponseID,LocationID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,*,...,NaN,59,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,NaN,...,NaN,1,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,NaN,...,NaN,2,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,NaN,...,NaN,4,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,NaN,...,NaN,5,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [39]:
del csv_df["QuestionID"]

csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,DataValueFootnoteSymbol,...,GeoLocation,ResponseID,LocationID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,*,...,NaN,NaN,59,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,NaN,...,"(32.84057112200048, -86.63186076199969)",NaN,1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,NaN,...,"(64.84507995700051, -147.72205903599973)",NaN,2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,NaN,...,"(34.865970280000454, -111.76381127699972)",NaN,4,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,NaN,...,"(34.74865012400045, -92.27449074299966)",NaN,5,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [40]:
del csv_df["DataValueTypeID"]

csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,DataValueFootnoteSymbol,...,Stratification3,GeoLocation,ResponseID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,*,...,NaN,NaN,NaN,59,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,NaN,...,NaN,"(32.84057112200048, -86.63186076199969)",NaN,1,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,NaN,...,NaN,"(64.84507995700051, -147.72205903599973)",NaN,2,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,NaN,...,NaN,"(34.865970280000454, -111.76381127699972)",NaN,4,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,NaN,...,NaN,"(34.74865012400045, -92.27449074299966)",NaN,5,OVERALL,OVR,NaN,NaN,NaN,NaN

In [41]:
del csv_df["StratificationCategoryID1"]

In [42]:
del csv_df["DataValueFootnoteSymbol"]

In [43]:
del csv_df["StratificationCategory3"]

In [44]:
del csv_df["Stratification3"]

In [45]:
del csv_df["DatavalueFootnote"]

In [46]:
del csv_df["LowConfidenceLimit"]

In [47]:
del csv_df["HighConfidenceLimit"]

In [48]:
del csv_df["StratificationCategory2"]

In [49]:
del csv_df["Stratification2"]

In [50]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,StratificationCategory1,Stratification1,GeoLocation,ResponseID,LocationID,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,Overall,Overall,NaN,NaN,59,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,Overall,Overall,"(32.84057112200048, -86.63186076199969)",NaN,1,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,Overall,Overall,"(64.84507995700051, -147.72205903599973)",NaN,2,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,Overall,Overall,"(34.865970280000454, -111.76381127699972)",NaN,4,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,Overall,Overall,"(34.74865012400045, -92.27449074299966)",NaN,5,OVR,NaN,NaN,NaN,NaN

In [51]:
del csv_df["Stratification1"]

In [52]:
del csv_df["ResponseID"]

In [53]:
del csv_df["LocationID"]

In [54]:
del csv_df["StratificationID1"]

In [55]:
del csv_df["StratificationCategoryID2"]

In [56]:
del csv_df["StratificationID2"]

In [57]:
del csv_df["StratificationCategoryID3"]

In [58]:
del csv_df["StratificationID3"]

In [59]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,StratificationCategory1,GeoLocation
0,2016,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.9,16.9,Overall,NaN
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,Overall,"(32.84057112200048, -86.63186076199969)"
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,Overall,"(64.84507995700051, -147.72205903599973)"
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,Overall,"(34.865970280000454, -111.76381127699972)"
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,Overall,"(34.74865012400045, -92.27449074299966)"

In [60]:
csv_df = csv_df.dropna(how="any")

In [61]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,DataValueAlt,StratificationCategory1,GeoLocation
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,13.0,Overall,"(32.84057112200048, -86.63186076199969)"
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,18.2,Overall,"(64.84507995700051, -147.72205903599973)"
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,15.6,Overall,"(34.865970280000454, -111.76381127699972)"
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,15.0,Overall,"(34.74865012400045, -92.27449074299966)"
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,16.3,Overall,"(37.63864012300047, -120.99999953799971)"

In [62]:
del csv_df["DataValueAlt"]

In [63]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,GeoLocation
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,"(32.84057112200048, -86.63186076199969)"
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,"(64.84507995700051, -147.72205903599973)"
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,"(34.865970280000454, -111.76381127699972)"
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,"(34.74865012400045, -92.27449074299966)"
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,"(37.63864012300047, -120.99999953799971)"

In [64]:
csv_df_2 = csv_df["GeoLocation"].str.split(",", n = 1, expand = True) 

csv_df_2.head()

                     0                      1
1   (32.84057112200048    -86.63186076199969)
2   (64.84507995700051   -147.72205903599973)
3  (34.865970280000454   -111.76381127699972)
4   (34.74865012400045    -92.27449074299966)
5   (37.63864012300047   -120.99999953799971)

In [65]:
# csv_df['tmp'] = 9
# csv_df_2['tmp'] = 2

## csv_df_3 = pd.merge(csv_df, csv_df_2, on=['tmp'])
# csv_df_3.head()

In [66]:
csv_df["Latitude"] = csv_df_2[0]
csv_df.head()

/Users/Pariah/anaconda3/envs/PythonData3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,GeoLocation,Latitude
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,"(32.84057112200048, -86.63186076199969)",(32.84057112200048
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,"(64.84507995700051, -147.72205903599973)",(64.84507995700051
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,"(34.865970280000454, -111.76381127699972)",(34.865970280000454
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,"(34.74865012400045, -92.27449074299966)",(34.74865012400045
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,"(37.63864012300047, -120.99999953799971)",(37.63864012300047

In [67]:
csv_df["Longitude"] = csv_df_2[1]
csv_df.head()

/Users/Pariah/anaconda3/envs/PythonData3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,GeoLocation,Latitude,Longitude
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,"(32.84057112200048, -86.63186076199969)",(32.84057112200048,-86.63186076199969)
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,"(64.84507995700051, -147.72205903599973)",(64.84507995700051,-147.72205903599973)
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,"(34.865970280000454, -111.76381127699972)",(34.865970280000454,-111.76381127699972)
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,"(34.74865012400045, -92.27449074299966)",(34.74865012400045,-92.27449074299966)
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,"(37.63864012300047, -120.99999953799971)",(37.63864012300047,-120.99999953799971)

In [70]:
del csv_df["GeoLocation"]

KeyError: 'GeoLocation'

In [71]:
# del csv_df["tmp"]

In [72]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,Latitude,Longitude
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,(32.84057112200048,-86.63186076199969)
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,(64.84507995700051,-147.72205903599973)
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,(34.865970280000454,-111.76381127699972)
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,(34.74865012400045,-92.27449074299966)
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,(37.63864012300047,-120.99999953799971)

In [73]:
replace_lat = csv_df["Latitude"].str.replace("\(","")
csv_df_4 = pd.DataFrame(replace_lat)
csv_df_4.head()

             Latitude
1   32.84057112200048
2   64.84507995700051
3  34.865970280000454
4   34.74865012400045
5   37.63864012300047

In [74]:
csv_df["Latitude2"] = csv_df_4["Latitude"]
csv_df.head()

/Users/Pariah/anaconda3/envs/PythonData3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,Latitude,Longitude,Latitude2
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,(32.84057112200048,-86.63186076199969),32.84057112200048
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,(64.84507995700051,-147.72205903599973),64.84507995700051
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,(34.865970280000454,-111.76381127699972),34.865970280000454
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,(34.74865012400045,-92.27449074299966),34.74865012400045
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,(37.63864012300047,-120.99999953799971),37.63864012300047

In [75]:
replace_lng = csv_df["Longitude"].str.replace("\)","")
csv_df_5 = pd.DataFrame(replace_lng)
csv_df_5.head()

              Longitude
1    -86.63186076199969
2   -147.72205903599973
3   -111.76381127699972
4    -92.27449074299966
5   -120.99999953799971

In [76]:
csv_df["Longitude2"] = csv_df_5["Longitude"]
csv_df.head()

/Users/Pariah/anaconda3/envs/PythonData3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,Latitude,Longitude,Latitude2,Longitude2
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,(32.84057112200048,-86.63186076199969),32.84057112200048,-86.63186076199969
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,(64.84507995700051,-147.72205903599973),64.84507995700051,-147.72205903599973
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,(34.865970280000454,-111.76381127699972),34.865970280000454,-111.76381127699972
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,(34.74865012400045,-92.27449074299966),34.74865012400045,-92.27449074299966
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,(37.63864012300047,-120.99999953799971),37.63864012300047,-120.99999953799971

In [77]:
del csv_df["Latitude"]

In [78]:
del csv_df["Longitude"]

In [79]:
csv_df = csv_df.rename(columns={
    "Longitude2": "Longitude",
    "Latitude2": "Latitude"
})

In [80]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,Latitude,Longitude
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13,Overall,32.84057112200048,-86.63186076199969
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,64.84507995700051,-147.72205903599973
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,34.865970280000454,-111.76381127699972
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15,Overall,34.74865012400045,-92.27449074299966
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,37.63864012300047,-120.99999953799971

In [81]:
csv_df.dtypes

YearStart                   int64
YearEnd                     int64
LocationAbbr               object
LocationDesc               object
Topic                      object
Question                   object
DataValueUnit              object
DataValue                  object
StratificationCategory1    object
Latitude                   object
Longitude                  object
dtype: object

In [82]:
csv_df["DataValue"] = csv_df["DataValue"].astype(float)

In [83]:
csv_df.dtypes

YearStart                    int64
YearEnd                      int64
LocationAbbr                object
LocationDesc                object
Topic                       object
Question                    object
DataValueUnit               object
DataValue                  float64
StratificationCategory1     object
Latitude                    object
Longitude                   object
dtype: object

In [84]:
csv_df["Longitude"] = csv_df["Longitude"].astype(float)
csv_df["Latitude"] = csv_df["Latitude"].astype(float)

In [85]:
csv_df.dtypes

YearStart                    int64
YearEnd                      int64
LocationAbbr                object
LocationDesc                object
Topic                       object
Question                    object
DataValueUnit               object
DataValue                  float64
StratificationCategory1     object
Latitude                   float64
Longitude                  float64
dtype: object

In [86]:
csv_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Topic,Question,DataValueUnit,DataValue,StratificationCategory1,Latitude,Longitude
1,2016,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,%,13.0,Overall,32.840571,-86.631861
2,2016,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,%,18.2,Overall,64.845080,-147.722059
3,2016,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.6,Overall,34.865970,-111.763811
4,2016,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,%,15.0,Overall,34.748650,-92.274491
5,2016,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,%,16.3,Overall,37.638640,-121.000000

In [87]:
output_csv = csv_df.to_csv("Cleaned_Chronic_Disease_Data_3.csv", index=False, header=True)